CREATE TABLE CUISINE (
CUISINE_ID IDENTITY NOT NULL PRIMARY KEY,
CUISINE_NAME VARCHAR(100)
);

INSERT INTO CUISINE (CUISINE_NAME) VALUES ('Chinese');
INSERT INTO CUISINE (CUISINE_NAME) VALUES ('Japanese');
INSERT INTO CUISINE (CUISINE_NAME) VALUES ('Thai');
INSERT INTO CUISINE (CUISINE_NAME) VALUES ('Korean');
INSERT INTO CUISINE (CUISINE_NAME) VALUES ('Malaysian');
INSERT INTO CUISINE (CUISINE_NAME) VALUES ('American');
INSERT INTO CUISINE (CUISINE_NAME) VALUES ('Western');
INSERT INTO CUISINE (CUISINE_NAME) VALUES ('Vietnamese');
INSERT INTO CUISINE (CUISINE_NAME) VALUES ('Vegetarian');
INSERT INTO CUISINE (CUISINE_NAME) VALUES ('Desert');
INSERT INTO CUISINE (CUISINE_NAME) VALUES ('Alcohol');


CREATE TABLE MENU (
ITEM_CODE IDENTITY NOT NULL PRIMARY KEY,
ITEM_NAME VARCHAR(100),
DESCRIPTION VARCHAR(255),
ITEM_CATEGORY VARCHAR(100),
PRICE NUMERIC(8,2),
QUANTITY INT,
RESTAURANT_ID INT
);

INSERT INTO MENU (ITEM_NAME, DESCRIPTION, ITEM_CATEGORY, PRICE, QUANTITY, RESTAURANT_ID) VALUES ('Chai tow kway', 'Chinese food', 'Chinese', 8.2, 100, 1);
INSERT INTO MENU (ITEM_NAME, DESCRIPTION, ITEM_CATEGORY, PRICE, QUANTITY, RESTAURANT_ID) VALUES ('Yakitori', 'Japanese food', 'Japanese', 9.5, 100, 2);
INSERT INTO MENU (ITEM_NAME, DESCRIPTION, ITEM_CATEGORY, PRICE, QUANTITY, RESTAURANT_ID) VALUES ('Pad Thai', 'Thai food', 'Thai', 7.6, 100, 3);
INSERT INTO MENU (ITEM_NAME, DESCRIPTION, ITEM_CATEGORY, PRICE, QUANTITY, RESTAURANT_ID) VALUES ('Jajang Myeon', 'Korean food', 'Korean', 9.3, 100, 4);
INSERT INTO MENU (ITEM_NAME, DESCRIPTION, ITEM_CATEGORY, PRICE, QUANTITY, RESTAURANT_ID) VALUES ('Nasi Lemak', 'Malaysian food', 'Malaysian', 6.8, 100, 5);
INSERT INTO MENU (ITEM_NAME, DESCRIPTION, ITEM_CATEGORY, PRICE, QUANTITY, RESTAURANT_ID) VALUES ('Clam Chowder', 'American food', 'American', 5.9, 100, 1);
INSERT INTO MENU (ITEM_NAME, DESCRIPTION, ITEM_CATEGORY, PRICE, QUANTITY, RESTAURANT_ID) VALUES ('Barbeque Chicken', 'Western food', 'Western', 6.3, 100, 2);
INSERT INTO MENU (ITEM_NAME, DESCRIPTION, ITEM_CATEGORY, PRICE, QUANTITY, RESTAURANT_ID) VALUES ('Drunken Prawn', 'Vietnamese food', 'Vietnamese', 8.4, 100, 3);
INSERT INTO MENU (ITEM_NAME, DESCRIPTION, ITEM_CATEGORY, PRICE, QUANTITY, RESTAURANT_ID) VALUES ('Leafy Greens', 'Vegetarian food', 'Vegetarian', 7.1, 100, 4);
INSERT INTO MENU (ITEM_NAME, DESCRIPTION, ITEM_CATEGORY, PRICE, QUANTITY, RESTAURANT_ID) VALUES ('Fo Tiao Qiang', 'Sweet soup', 'Desert', 4.5, 100, 5);
INSERT INTO MENU (ITEM_NAME, DESCRIPTION, ITEM_CATEGORY, PRICE, QUANTITY, RESTAURANT_ID) VALUES ('Cosmopolitan', 'Alcohol drink', 'Alcohol', 5.2, 100, 1);


CREATE TABLE RESTAURANT (
RESTAURANT_ID IDENTITY NOT NULL PRIMARY KEY,
RESTAURANT_NAME VARCHAR(100),
DESCRIPTION VARCHAR(255),
STREET_ADDRESS VARCHAR(255),
CITY VARCHAR(100),
STATE VARCHAR(100),
POSTAL VARCHAR(10),
WEBSITE VARCHAR(250),
PHONE_NUMBER VARCHAR(50),
CUISINE_ID INT,
RESTAURANT_IMAGE VARCHAR(250),
OWNER_ID VARCHAR(50)
);

INSERT INTO RESTAURANT (RESTAURANT_NAME, DESCRIPTION, STREET_ADDRESS, CITY, STATE, POSTAL, WEBSITE, PHONE_NUMBER, CUISINE_ID, RESTAURANT_IMAGE, OWNER_ID) VALUES ('Corner House', 'Elegant, upscale restaurant in 1910 bungalow with verandah, offering inventive global dishes', '1 Cluny Rd, E J H Corner House', 'Botanic Gardens', 'Singapore', '259569', 'cornerhouse.com.sg', '64691000', 1, 'rest-1.jpg', 'ryan');
INSERT INTO RESTAURANT (RESTAURANT_NAME, DESCRIPTION, STREET_ADDRESS, CITY, STATE, POSTAL, WEBSITE, PHONE_NUMBER, CUISINE_ID, RESTAURANT_IMAGE, OWNER_ID) VALUES ('Flutes', 'Fine dining restaurant', '93 Stamford Rd, #01-02 National Museum of Singapore', 'Brah Basah', 'Singapore', '178897', 'foodbooking.com', '63388770', 2, 'rest-2.jpg', 'ryan');
INSERT INTO RESTAURANT (RESTAURANT_NAME, DESCRIPTION, STREET_ADDRESS, CITY, STATE, POSTAL, WEBSITE, PHONE_NUMBER, CUISINE_ID, RESTAURANT_IMAGE, OWNER_ID) VALUES ('Whitegrass Restaurant', 'Stylish eatery offering elevated & modern French fare with Japanese techniques plus cocktails', '30 Victoria St, #01-26/27 Chijmes', 'City Hall', 'Singapore', '187996', 'whitegrass.com.sg', '68370402', 3, 'rest-3.jpg', 'ryan');
INSERT INTO RESTAURANT (RESTAURANT_NAME, DESCRIPTION, STREET_ADDRESS, CITY, STATE, POSTAL, WEBSITE, PHONE_NUMBER, CUISINE_ID, RESTAURANT_IMAGE, OWNER_ID) VALUES ('Candlenut', 'Refined Peranakan cuisine & an ample wine list offered in a lofty, rustic-chic setting', '17A Dempsey Rd', 'Holland Village', 'Singapore', '249676', 'comodempsey.sg', '18003042288', 4, 'rest-4.jpg', 'ryan');
INSERT INTO RESTAURANT (RESTAURANT_NAME, DESCRIPTION, STREET_ADDRESS, CITY, STATE, POSTAL, WEBSITE, PHONE_NUMBER, CUISINE_ID, RESTAURANT_IMAGE, OWNER_ID) VALUES ('Tippling Club', 'Contemporary, artful spot offering an inventive, gourmet tasting menu and ambitious cocktails', '38 Tanjong Pagar Rd', 'China Town', 'Singapore', '088461', 'tipplingclub.com', '64752217', 5, 'rest-5.jpg', 'ryan');


CREATE TABLE REVIEW (
REVIEW_NUMBER IDENTITY NOT NULL PRIMARY KEY,
RESTAURANT_ID INT,
USER_ID NVARCHAR(50),
RATING INT,
COMMENTS NVARCHAR(255),
REVIEW_DATETIME NVARCHAR(100)
);


CREATE TABLE MEMBER (
USER_ID VARCHAR(50) PRIMARY KEY,
USER_PASSWORD NVARCHAR(100),
FIRST_NAME  NVARCHAR(30),
MIDDLE_NAME  NVARCHAR(30),
LAST_NAME  NVARCHAR(30),
STREET_ADDRESS  NVARCHAR(255),
CITY  NVARCHAR(100),
STATE  NVARCHAR(100),
POSTAL  NVARCHAR(10),
PHONE_NUMBER  NVARCHAR(25),
EMAIL  NVARCHAR(100),
CC_NUMBER  NVARCHAR(25),
CARD_TYPE  NVARCHAR(50),
CC_EXPIRY_YY INT,
CC_EXPIRY_MM INT,
CC_HOLDER_NAME  NVARCHAR(100)
);

INSERT INTO MEMBER (USER_ID, USER_PASSWORD, FIRST_NAME, MIDDLE_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, POSTAL, PHONE_NUMBER, EMAIL, CC_NUMBER, CARD_TYPE, CC_EXPIRY_YY, CC_EXPIRY_MM, CC_HOLDER_NAME)
VALUES ('ryan','ryan','Ryan','KH','Le','18 Clementi Ave 1','Singapore','Singapore','129961','06583196305','ryanle.sg@gmail.com','4567-8901-2345-6789','VISA',2022,9,'RYAN LE KIM HOANG');
